"""Downloader tests (M1.8 + M1.9) — httpx.MockTransport only, no network.

Covers success + hash correctness against a Pillow-generated fixture, 404,
5xx retry, retry exhaustion, size limits (header and mid-stream), content-type
rejection/mismatch, GIF + MP4/WebM video support, redirect following, atomic
writes (no partial files), filename sanitization/path traversal, and the
Level-1 URL duplicate skip callback (PRD §11, §12, §41, §52).
"""

from __future__ import annotations

import asyncio
import hashlib
from collections.abc import AsyncIterator, Callable
from pathlib import Path

import httpx

from backend.scraper.adapters import CommentMeta, MediaRef
from backend.scraper.downloader import (
    DownloadStatus,
    Downloader,
    sanitize_filename,
)

CDN = "https://cdn.example.com/media"

#: Minimal MP4 (ftyp box at offset 4) and WebM (EBML magic) container headers.
MP4_BYTES = b"\x00\x00\x00\x18ftypisom\x00\x00\x00\x00isomiso2avc1mp41" + b"\x00" * 64
WEBM_BYTES = b"\x1a\x45\xdf\xa3\x01\x00\x00\x00\x00\x00\x00\x1f" + b"\x00" * 64

Handler = Callable[[httpx.Request], httpx.Response]


def media_ref(url: str, *, original_filename: str | None = None) -> MediaRef:
    return MediaRef(
        url=url,
        kind="image",
        comment=CommentMeta(comment_id="42", author_name="tester"),
        original_filename=original_filename,
    )


def make_client(handler: Handler) -> httpx.AsyncClient:
    return httpx.AsyncClient(transport=httpx.MockTransport(handler), follow_redirects=True)


def make_downloader(
    destination: Path, client: httpx.AsyncClient, make_settings, **crawler_overrides
) -> Downloader:
    return Downloader(
        destination_dir=destination,
        settings=make_settings(**crawler_overrides),
        client=client,
    )


def png_bytes(sample_images: dict[str, Path]) -> bytes:
    return sample_images["png"].read_bytes()


async def test_success_writes_file_and_correct_sha256(
    tmp_path: Path, make_settings, sample_images: dict[str, Path]
) -> None:
    """Hash matches hashlib over Pillow-generated bytes; no temp files remain (PRD §11)."""
    body = png_bytes(sample_images)
    destination = tmp_path / "media"

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(200, content=body, headers={"content-type": "image/png"})

    client = make_client(handler)
    downloader = make_downloader(destination, client, make_settings)
    try:
        result = await downloader.download(media_ref(f"{CDN}/meme.png"))
    finally:
        await client.aclose()

    assert result.ok
    assert result.status is DownloadStatus.OK
    assert result.path == destination / "meme.png"
    assert result.path.is_file()
    assert result.path.read_bytes() == body
    assert result.sha256 == hashlib.sha256(body).hexdigest()
    assert result.size == len(body)
    assert result.content_type == "image/png"
    assert result.kind == "image"
    assert [entry.name for entry in destination.iterdir()] == ["meme.png"]


async def test_404_fails_immediately_without_retry(tmp_path: Path, make_settings) -> None:
    calls: list[int] = []

    def handler(request: httpx.Request) -> httpx.Response:
        calls.append(1)
        return httpx.Response(404)

    destination = tmp_path / "media"
    client = make_client(handler)
    downloader = make_downloader(destination, client, make_settings)
    try:
        result = await downloader.download(media_ref(f"{CDN}/gone.png"))
    finally:
        await client.aclose()

    assert not result.ok
    assert result.status is DownloadStatus.FAILED
    assert result.error == "HTTP 404"
    assert len(calls) == 1
    assert list(destination.iterdir()) == []  # atomicity: nothing at the final path


async def test_500_then_success_retries_with_backoff(tmp_path: Path, make_settings) -> None:
    calls: list[int] = []

    def handler(request: httpx.Request) -> httpx.Response:
        calls.append(1)
        if len(calls) == 1:
            return httpx.Response(500)
        return httpx.Response(200, content=MP4_BYTES, headers={"content-type": "video/mp4"})

    destination = tmp_path / "media"
    client = make_client(handler)
    downloader = make_downloader(destination, client, make_settings, retry_attempts=3)
    try:
        result = await downloader.download(media_ref(f"{CDN}/clip.mp4"))
    finally:
        await client.aclose()

    assert result.ok
    assert result.kind == "video"
    assert len(calls) == 2


async def test_gives_up_after_configured_attempts(tmp_path: Path, make_settings) -> None:
    calls: list[int] = []

    def handler(request: httpx.Request) -> httpx.Response:
        calls.append(1)
        return httpx.Response(503)

    destination = tmp_path / "media"
    client = make_client(handler)
    downloader = make_downloader(destination, client, make_settings, retry_attempts=2)
    try:
        result = await downloader.download(media_ref(f"{CDN}/sick.png"))
    finally:
        await client.aclose()

    assert not result.ok
    assert "failed after 2 attempts" in (result.error or "")
    assert len(calls) == 2
    assert list(destination.iterdir()) == []


async def test_oversized_rejected_by_content_length(tmp_path: Path, make_settings) -> None:
    oversized = b"x" * (1024 * 1024 + 512)  # > max_file_size_mb = 1

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(200, content=oversized, headers={"content-type": "image/png"})

    destination = tmp_path / "media"
    client = make_client(handler)
    downloader = make_downloader(destination, client, make_settings, max_file_size_mb=1)
    try:
        result = await downloader.download(media_ref(f"{CDN}/huge.png"))
    finally:
        await client.aclose()

    assert not result.ok
    assert "exceeds size limit" in (result.error or "")
    assert list(destination.iterdir()) == []


async def test_oversized_aborts_mid_stream_without_content_length(
    tmp_path: Path, make_settings
) -> None:
    async def stream_body() -> AsyncIterator[bytes]:
        for _ in range(40):
            yield b"x" * 65536  # 2.5 MiB total, no Content-Length header

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(200, content=stream_body(), headers={"content-type": "image/png"})

    destination = tmp_path / "media"
    client = make_client(handler)
    downloader = make_downloader(destination, client, make_settings, max_file_size_mb=1)
    try:
        result = await downloader.download(media_ref(f"{CDN}/streamed.png"))
    finally:
        await client.aclose()

    assert not result.ok
    assert "exceeds size limit" in (result.error or "")
    assert list(destination.iterdir()) == []  # temp file cleaned up, no partial at final path


async def test_bad_content_type_rejected(tmp_path: Path, make_settings) -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(200, content=b"<!doctype html><html>error</html>",
                              headers={"content-type": "text/html"})

    destination = tmp_path / "media"
    client = make_client(handler)
    downloader = make_downloader(destination, client, make_settings)
    try:
        result = await downloader.download(media_ref(f"{CDN}/not-media"))
    finally:
        await client.aclose()

    assert not result.ok
    assert result.error == "unsupported content type: text/html"
    assert list(destination.iterdir()) == []


async def test_content_type_mismatch_rejected(
    tmp_path: Path, make_settings, sample_images: dict[str, Path]
) -> None:
    """Declared image/png but the bytes are a GIF — rejected as corrupt/mislabeled (PRD §11)."""
    body = sample_images["gif"].read_bytes()

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(200, content=body, headers={"content-type": "image/png"})

    destination = tmp_path / "media"
    client = make_client(handler)
    downloader = make_downloader(destination, client, make_settings)
    try:
        result = await downloader.download(media_ref(f"{CDN}/liar.png"))
    finally:
        await client.aclose()

    assert not result.ok
    assert "content type mismatch" in (result.error or "")
    assert list(destination.iterdir()) == []


async def test_missing_content_type_sniffed_from_magic(
    tmp_path: Path, make_settings, sample_images: dict[str, Path]
) -> None:
    body = png_bytes(sample_images)

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(200, content=body)  # httpx sends no Content-Type for raw bytes

    destination = tmp_path / "media"
    client = make_client(handler)
    downloader = make_downloader(destination, client, make_settings)
    try:
        result = await downloader.download(media_ref(f"{CDN}/sniffed"))
    finally:
        await client.aclose()

    assert result.ok
    assert result.content_type == "image/png"
    assert result.kind == "image"
    assert result.path is not None and result.path.suffix == ".png"


async def test_gif_download_classified_as_gif(
    tmp_path: Path, make_settings, sample_images: dict[str, Path]
) -> None:
    body = sample_images["gif"].read_bytes()

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(200, content=body, headers={"content-type": "image/gif"})

    destination = tmp_path / "media"
    client = make_client(handler)
    downloader = make_downloader(destination, client, make_settings)
    try:
        result = await downloader.download(media_ref(f"{CDN}/reaction.gif"))
    finally:
        await client.aclose()

    assert result.ok
    assert result.kind == "gif"
    assert result.path is not None and result.path.name == "reaction.gif"


async def test_mp4_video_downloaded(tmp_path: Path, make_settings) -> None:
    """M1.9: MP4 comment attachments are accepted and stored."""

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(200, content=MP4_BYTES, headers={"content-type": "video/mp4"})

    destination = tmp_path / "media"
    client = make_client(handler)
    downloader = make_downloader(destination, client, make_settings)
    try:
        result = await downloader.download(media_ref(f"{CDN}/nodoubt.mp4"))
    finally:
        await client.aclose()

    assert result.ok
    assert result.kind == "video"
    assert result.content_type == "video/mp4"
    assert result.path is not None and result.path.read_bytes() == MP4_BYTES


async def test_webm_video_downloaded(tmp_path: Path, make_settings) -> None:
    """M1.9: WebM comment attachments are accepted and stored."""

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(200, content=WEBM_BYTES, headers={"content-type": "video/webm"})

    destination = tmp_path / "media"
    client = make_client(handler)
    downloader = make_downloader(destination, client, make_settings)
    try:
        result = await downloader.download(media_ref(f"{CDN}/eyroll.webm"))
    finally:
        await client.aclose()

    assert result.ok
    assert result.kind == "video"
    assert result.path is not None and result.path.read_bytes() == WEBM_BYTES


async def test_redirects_are_followed(
    tmp_path: Path, make_settings, sample_images: dict[str, Path]
) -> None:
    body = png_bytes(sample_images)

    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path == "/old.png":
            return httpx.Response(307, headers={"location": "/new.png"})
        return httpx.Response(200, content=body, headers={"content-type": "image/png"})

    destination = tmp_path / "media"
    client = make_client(handler)
    downloader = make_downloader(destination, client, make_settings)
    try:
        result = await downloader.download(media_ref(f"{CDN}/old.png"))
    finally:
        await client.aclose()

    assert result.ok
    assert result.path == destination / "old.png"


async def test_url_duplicate_skipped_without_network(tmp_path: Path, make_settings) -> None:
    calls: list[int] = []

    def handler(request: httpx.Request) -> httpx.Response:
        calls.append(1)
        return httpx.Response(200)

    destination = tmp_path / "media"
    client = make_client(handler)
    downloader = Downloader(
        destination_dir=destination,
        settings=make_settings(),
        client=client,
        url_already_downloaded=lambda url: True,
    )
    try:
        result = await downloader.download(media_ref(f"{CDN}/seen-before.png"))
    finally:
        await client.aclose()

    assert result.status is DownloadStatus.DUPLICATE_URL
    assert not result.ok
    assert calls == []  # Level-1 check happens before any request (PRD §12)
    assert not destination.exists() or list(destination.iterdir()) == []


async def test_path_traversal_in_target_name_neutralized(
    tmp_path: Path, make_settings, sample_images: dict[str, Path]
) -> None:
    body = png_bytes(sample_images)

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(200, content=body, headers={"content-type": "image/png"})

    destination = tmp_path / "media"
    client = make_client(handler)
    downloader = make_downloader(destination, client, make_settings)
    try:
        result = await downloader.download(
            media_ref(f"{CDN}/evil.png"), target_name="../../evil.png"
        )
        backslash = await downloader.download(
            media_ref(f"{CDN}/evil2.png"), target_name="..\\..\\evil2.png"
        )
    finally:
        await client.aclose()

    assert result.ok and result.path == destination / "evil.png"
    assert backslash.ok and backslash.path == destination / "evil2.png"
    assert (destination / "evil.png").is_file()
    assert not (destination.parent.parent / "evil.png").exists()


async def test_original_filename_and_url_basename_used(
    tmp_path: Path, make_settings, sample_images: dict[str, Path]
) -> None:
    body = png_bytes(sample_images)

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(200, content=body, headers={"content-type": "image/png"})

    destination = tmp_path / "media"
    client = make_client(handler)
    downloader = make_downloader(destination, client, make_settings)
    try:
        named = await downloader.download(
            media_ref(f"{CDN}/whatever.png", original_filename="My Meme.png")
        )
        from_url = await downloader.download(media_ref(f"{CDN}/dir/funny-meme.gif?sig=abc"))
        no_ext = await downloader.download(media_ref(f"{CDN}/bare"))
    finally:
        await client.aclose()

    assert named.path == destination / "My Meme.png"
    # URL basename wins only without original_filename; a missing extension is
    # appended from the sniffed content type (a provided one is kept as-is).
    assert from_url.path == destination / "funny-meme.gif"
    assert no_ext.path == destination / "bare.png"


def test_sanitize_filename_blocks_traversal_and_reserved_names() -> None:
    assert sanitize_filename("../../etc/passwd") == "passwd"
    assert sanitize_filename("..\\..\\windows\\system32\\evil.png") == "evil.png"
    assert sanitize_filename("..%2f..%2fevil.png") == "evil.png"
    assert sanitize_filename('a<b>|c?.png') == "a_b__c_.png"
    assert sanitize_filename("CON.png") == "_CON.png"
    assert sanitize_filename("nul.txt") == "_nul.txt"
    assert sanitize_filename("  ..  ") == "download"
    assert sanitize_filename("") == "download"
    assert sanitize_filename(".hidden.png") == "hidden.png"
    long_name = "x" * 300 + ".png"
    assert len(sanitize_filename(long_name)) <= 116


def test_aclose_keeps_injected_client_open(make_settings) -> None:
    client = make_client(lambda request: httpx.Response(200))
    downloader = Downloader(destination_dir=Path("."), settings=make_settings(), client=client)

    async def close_and_probe() -> None:
        await downloader.aclose()
        response = await client.get("https://fixture.test/still-open")
        assert response.status_code == 200
        await client.aclose()

    asyncio.run(close_and_probe())
